### 이름으로 유저 조회

GET localhost:8080/api/user/kim
Content-Type: application/json

### 없는 이름으로 유저 조회

GET localhost:8080/api/user/no
Content-Type: application/json

### 유저 회원가입

POST localhost:8080/api/user
Content-Type: application/json

{
  "name" : "newUser",
  "email": "newUser@test.com",
  "password": "1234"
}

### 유저 회원가입 실패 (이름 공백)
POST localhost:8080/api/user
Content-Type: application/json

{
  "name" : "",
  "email": "newUser@test.com",
  "password": "1234"
}

### 유저 회원가입 실패 (이름 누락)
POST localhost:8080/api/user
Content-Type: application/json

{
  "email": "newUser@test.com",
  "password": "1234"
}

### 유저 회원가입 실패 (이메일 공백)

POST localhost:8080/api/user
Content-Type: application/json

{
  "name" : "newUser",
  "email": "",
  "password": "1234"
}

### 유저 회원가입 실패 (이메일 누락)

POST localhost:8080/api/user
Content-Type: application/json

{
  "name" : "newUser",
  "password": "1234"
}

### 유저 회원가입 실패 (이메일 형식)

POST localhost:8080/api/user
Content-Type: application/json

{
  "name" : "newUser",
  "email": "test",
  "password": "1234"
}

### 유저 회원가입 실패 (이메일 중복)

POST localhost:8080/api/user
Content-Type: application/json

{
  "name" : "newUser",
  "email": "regular@test.com",
  "password": "1234"
}

### 유저 회원가입 실패 (이름 누락, 이메일 형식, 비밀번호 공백)

POST localhost:8080/api/user
Content-Type: application/json

{
  "email": "invalidEmailFormat",
  "password": ""
}