@adId = 1
@noExist = -1

### 광고 정보 업데이트 - 정상
PATCH localhost:8080/ap1/v1/ad/{{adId}}/info
Content-Type: application/json

{
  "title": "updatedAdTitle",
  "desc": "updated ad desc"
}

### 광고 정보 업데이트 - 정상 - 설명 누락
PATCH localhost:8080/ap1/v1/ad/{{adId}}/info
Content-Type: application/json

{
  "title": "updatedAdTitle"
}

### 광고 정보 업데이트 - 없는 광고
PATCH localhost:8080/ap1/v1/ad/{{noExist}}/info
Content-Type: application/json

{
  "title": "updatedAdTitle",
  "desc": "updated ad desc"
}

### 광고 정보 업데이트 - 제목 공란
PATCH localhost:8080/ap1/v1/ad/{{adId}}/info
Content-Type: application/json

{
  "title": " ",
  "desc": "updated ad desc"
}

### 광고 정보 업데이트 - 제목 누락
PATCH localhost:8080/ap1/v1/ad/{{adId}}/info
Content-Type: application/json

{
  "desc": "updated ad desc"
}

### 광고 정보 업데이트 - 잘못된 바디
PATCH localhost:8080/ap1/v1/ad/{{adId}}/info
Content-Type: application/json

{
  "title" : "whatwhat?",
  "what?" : "what?",
  "desc": "updated ad desc"
}