@adId = 1
@noExistAd = -1

### 광고 검색 - 정상
GET localhost:8080/api/v1/ad/{{adId}}
Content-Type: application/json

### 광고 검색 - 실패
GET localhost:8080/api/v1/ad/{{noExistAd}}
Content-Type: application/json