### 비디오 상태 변경 - ARCHIVED
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "videoStatus": "ARCHIVED"
}

### 비디오 상태 변경 - DELETE
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "videoStatus": "DELETED"
}

### 비디오 상태 변경 - 정의되지 않은 상태
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "videoStatus": "noExist"
}

### 비디오 상태 변경 - 상태값 공란
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "videoStatus": " "
}

### 비디오 상태 변경 - 상태값 누락
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
}