### 비디오 수정 - 정상
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "title": "updatedTitle",
  "desc": "updated desc for a test vid",
  "email": "regular@test.com"
}

### 비디오 수정 - 정상 - 설명 누락
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "title": "updatedTitle",
  "desc": "",
  "email": "regular@test.com"
}


### 비디오 수정 - 제목 누락
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "title": "",
  "desc": "updated desc for a test vid",
  "email": "regular@test.com"
}

### 비디오 수정 - 없는 비디오
PATCH localhost:8080/api/video/-1/status
Content-Type: application/json

{
  "title": "updatedVideoTitle",
  "desc": "updated desc for a test vid",
  "email": "regular@test.com"
}

### 비디오 수정 - 없는 유저
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "title": "updatedVideoTitle",
  "desc": "updated desc for a test vid",
  "email": "noexist@test.com"
}

### 비디오 수정 - 주인이 아닌 유저
PATCH localhost:8080/api/video/1/status
Content-Type: application/json

{
  "title": "updatedVideoTitle",
  "desc": "updated desc for a test vid",
  "email": "park@test.com"
}