@default = 1
@guest = 2

### 비디오 업로드 - 정상
POST localhost:8080/ap1/v1/video/{{default}}
Content-Type: application/json

{
  "title": "testVideo999",
  "videoLength" : 3600,
  "desc": "new video upload test"
}

### 비디오 업로드 - 유저가 기본상태가 아님
POST localhost:8080/ap1/v1/video/{{guest}}
Content-Type: application/json

{
  "title": "testVideo",
  "videoLength" : 5666,
  "desc": "new video upload test"
}

### 비디오 업로드 - 존재하지 않는 유저
POST localhost:8080/ap1/v1/video/-1
Content-Type: application/json

{
  "title": "testVideo",
  "videoLnegth": 63213,
  "desc": "new video upload test"
}
