### 비디오 업로드 - 정상
POST localhost:8080/api/video
Content-Type: application/json

{
  "title": "testVideo",
  "desc": "new video upload test",
  "userEmail": "regular@test.com"
}

### 비디오 업로드 - 유저가 업로더가 아님
POST localhost:8080/api/video
Content-Type: application/json

{
  "title": "testVideo",
  "desc": "new video upload test",
  "userEmail": "park@test.com"
}

### 비디오 업로드 - 존재하지 않는 유저
POST localhost:8080/api/video
Content-Type: application/json

{
  "title": "testVideo",
  "desc": "new video upload test",
  "userEmail": "noexist@test.com"
}
